# Dependencies
gems:                [jekyll-paginate]
markdown:            kramdown
#highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           none
#relative_permalinks: true

# Setup
title:               Amiya Sahu
tagline:             "Web Developer"
description:         'I am a Web Developer, Blogger and Coffee addict.Java developer by profession, Q2A developer by addiction.This is my personal website where I write few stuff which could be useful for other developers.'
url:                 https://localhost:4000
baseurl:             
paginate:            10

# About/contact
author:
  name:              Amiya Sahu
  url:               https://twitter.com/Amiya_Sahu
  email:             amiya053@gmail.com

# Custom vars
version:             1.0.0

#asset version will get upgraded once there is a new version released
asset_version:       1.0.0

# This website's repo
github:
  profile:        https://github.com/amiyasahu
  repo:           https://github.com/amiyasahu/amiyasahu.github.io

exclude:
  - templates
  - LICENSE.md
  - README.md
  - LICENSE.lanyon
  - README.lanyon

## "Jekyll Now" template stuff here
# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: amiya053@gmail.com
  facebook: sahu.amiya
  flickr:
  github: amiyasahu
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: 
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: 

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-57146880-1

#additional settings 
envrionment : prod    #defines which envriment it is running